### ISSUE TITLE
is it better to create a PhaseType and export it in index.ts?

### ISSUE THREAD

**Issue by Rhodanthe1116** [jokarz/react-typing-game-hook#1]
I'm using this hook and feel if there is a PhaseType, it would be more readable. 
See the example below:

```js
enum PhaseType {
    HAVENTSTARTED = 0,
    STARTED,
    ENDED,
}
```

I'm new to TypeScript so I didn't know what the best way is.
Just want to provide some feedback.😀

**Comment by jokarz** [comment]
Hey there @Rhodanthe1116  thanks again for using this hook, appreciate the feedback! 


We could change `HAVENTSTARTED` to `NOT_STARTED`, otherwise, your enum example is 👍
I could add this in for the next update

**Comment by Rhodanthe1116** [comment]
Thanks!

**Comment by jokarz** [comment]
Hey, just a heads up, it is updated👍. I went with camel casing to encourage users to use it as a whole like `PhaseType.NotStarted` over `NOT_STARTED` for code readability. I'm gonna be closing this but feel free to open another if there are other issues.

**Comment by Rhodanthe1116** [comment]
Thanks for your fast updating!
